export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  NEWS: '/news',
  SHOWROOM: '/showroom',
  CONTACT: '/contact',
  CART: '/cart',
  CHECKOUT: '/checkout',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  ORDERS: '/profile/orders',
  ORDER_DETAIL: '/profile/orders/:id',
  ADDRESSES: '/profile/addresses',
  WISHLIST: '/profile/wishlist',
  CHANGE_PASSWORD: '/profile/change-password',
};
